In [1]:
import torch
import torch.nn.functional as F
from torch import nn, optim
from torch.utils.data import TensorDataset, DataLoader

In [14]:
a = torch.Tensor([[1,0,0,2], [2,2,2,3], [1,0,0,0], [10,20,100,2]])
b = torch.Tensor([[5,1,0,0], [2,1,40,3], [1,1,1,1], [1,2,3,4]])
print(a)
print(b)

tensor([[  1.,   0.,   0.,   2.],
        [  2.,   2.,   2.,   3.],
        [  1.,   0.,   0.,   0.],
        [ 10.,  20., 100.,   2.]])
tensor([[ 5.,  1.,  0.,  0.],
        [ 2.,  1., 40.,  3.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.]])


In [21]:
def loss(predict, target):
    return (predict - target)**2 / (1/torch.max(torch.max(predict), torch.max(target)) + predict * target)

In [22]:
loss(a, b)

tensor([[  3.1936, 100.0000,   0.0000, 400.0000],
        [  0.0000,   0.4975,  18.0477,   0.0000],
        [  0.0000, 100.0000, 100.0000, 100.0000],
        [  8.0919,   8.0980,  31.3623,   0.4994]])

In [8]:
a, b

(tensor([[1., 0., 0., 2.]]), tensor([[5., 1., 0., 0.]]))

In [10]:
c = a
c

tensor([[1., 0., 0., 2.]])