In [1]:
import numpy as np

a = np.array([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]]])
b = np.array([[22,23],[24,25]])

a = a[1:]

In [2]:
a

array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [3]:
a.shape, b.shape

((2, 2, 2), (2, 2))

In [4]:
b = b.reshape(-1,*b.shape)
b.shape

(1, 2, 2)

In [5]:
np.concatenate((a,b))

array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[22, 23],
        [24, 25]]])

In [6]:
import re

pattern = re.compile('(?<=sl)\d+(?=-)')
path = 'trained_models/LSTM-sl25-bs512-lr0.001-nl2-dp0.5.pt'
pattern.findall(path)[0]

'25'

In [7]:
import torch

In [8]:
ts = torch.Tensor([1,2,3,4,5])
ts

tensor([1., 2., 3., 4., 5.])

In [9]:
ts[3:]

tensor([4., 5.])

In [10]:
torch.cat((ts[1:], torch.Tensor([6])))

tensor([2., 3., 4., 5., 6.])

In [11]:
path = 'trained_models/LSTM-is14283-os14283-sl12-bs256-lr0.001-nl3-dp0.5.pt'
name = path.split('/')[1]
name

'LSTM-is14283-os14283-sl12-bs256-lr0.001-nl3-dp0.5.pt'

In [12]:
pattern = re.compile('(?<=is)\d*')
pattern.findall(name)[0]

'14283'

In [13]:
import models

In [14]:
models.__dict__

{'__name__': 'models',
 '__doc__': '\nCopyright <2019> <COPYRIGHT Pingcheng Zhang>\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the "Software"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies\nof the Software, and to permit persons to whom the Software is furnished to do\nso, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT

In [15]:
models.__dict__['VanillaStateLSTM']

models.VanillaStateLSTM