# How to make your Pandas code faster

### 1. Accelerated Array Computing

In [1]:
import numpy as np
import pandas as pd
from numba import jit

# node numbers of the graph
nodes = np.arange(0, 6, 1)

# generate random fake connections
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])

In [2]:
record

array([[1, 4],
       [2, 4],
       [4, 3],
       ...,
       [5, 2],
       [3, 0],
       [4, 4]])

In [3]:
# create adjacency matrix:
am = np.zeros((len(nodes), len(nodes)))
am

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
# simple iterate through the records:
for row, col in record:
    
    am[row, col] += 1
    
am  

array([[148., 156., 194., 153., 178., 177.],
       [168., 150., 188., 163., 166., 177.],
       [185., 151., 173., 177., 157., 179.],
       [161., 148., 187., 163., 154., 162.],
       [153., 159., 161., 176., 168., 178.],
       [160., 173., 169., 169., 150., 169.]])

In [5]:
# let's wrap the above code into function and time it:

def adjacent1(record, am):
    for row, col in record:
        am[row, col] += 1
    return am

# clear history
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
am = np.zeros((len(nodes), len(nodes)))

In [6]:
%timeit adjacent1(record, am)

7.68 ms ± 55.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
# let's use the power of numba

@jit(nopython=True, parallel=True)
def adjacent2(record, am):
    for row in range(record.shape[0]):
        am[record[row,:][0], record[row, :][1]] += 1 # this twisted roundabout is due to not supported feature for iterating 2d arrays
    return am

# clear history
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
am = np.zeros((len(nodes), len(nodes)))

In [8]:
%timeit adjacent2(record, am)

8.7 µs ± 2.3 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 2. Converting a Pandas DataFrame to Numpy array

In [9]:
# let's create a pandas df from `record`

df_record = pd.DataFrame(record, columns=['o', 'd'])
df_record

o  d
0     1  2
1     3  1
2     2  2
3     4  3
4     0  5
5     4  0
6     2  3
7     5  2
8     1  4
9     4  3
10    3  0
11    2  3
12    0  0
13    2  2
14    1  1
15    1  3
16    5  4
17    2  5
18    1  1
19    4  1
20    1  0
21    4  0
22    3  1
23    5  1
24    4  3
25    1  0
26    0  3
27    2  2
28    1  5
29    5  3
...  .. ..
5970  0  0
5971  1  3
5972  1  5
5973  2  1
5974  2  2
5975  5  4
5976  0  5
5977  2  0
5978  4  2
5979  3  5
5980  5  0
5981  0  1
5982  0  1
5983  2  5
5984  0  2
5985  3  3
5986  2  1
5987  4  5
5988  5  2
5989  0  3
5990  5  4
5991  5  1
5992  3  5
5993  1  0
5994  2  3
5995  1  0
5996  1  0
5997  2  2
5998  0  5
5999  0  3

[6000 rows x 2 columns]

In [10]:
# let's rewrite adjacent function with pandas

def adjacent3(record, am):
    for _, row in record.iterrows():
        am[row['o'], row['d']] += 1
    return am

# clear history
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
df_record = pd.DataFrame(record, columns=['o', 'd'])
am = np.zeros((len(nodes), len(nodes)))

In [11]:
# time the pandas version
%timeit adjacent3(df_record, am)

358 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
# suppose the df_record is what we have in the first place.
# we want to leverage numba power to speed up our code
# so have to convert pandas df to numpy array first:

def adjacent4(record, am):
    record = record.to_numpy()
    record = record[1:, :]
    
    return adjacent2(record, am)

# clear history
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
df_record = pd.DataFrame(record, columns=['o', 'd'])
am = np.zeros((len(nodes), len(nodes)))    

In [13]:
%timeit adjacent4(df_record, am)

15.5 µs ± 43.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


The convertion from pandas dataframe to numpy array slows down more than 7 times compared with adjacent2.

Thus it is not a good idea to use a lot of pandas if you are performance sensitive.

However, it is still 35.1ms / 8.3us ~= 4000+ times faster!

We can expect that more rows the record got, the more obvious is the acceleration:

When set record has 6000 rows (10 times), the speed boost is 355ms / 15.3us ~= 20000+

In [14]:
# let's go through a real call:
# clear history
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
df_record = pd.DataFrame(record, columns=['o', 'd'])
am = np.zeros((len(nodes), len(nodes)))

res = adjacent4(df_record, am)
res

array([[169., 168., 175., 173., 156., 174.],
       [179., 172., 183., 151., 172., 170.],
       [165., 160., 148., 197., 165., 166.],
       [159., 177., 162., 172., 155., 148.],
       [151., 176., 170., 166., 165., 170.],
       [187., 150., 144., 176., 156., 172.]])

In [15]:
# another real call of the slow pandas version:
record = np.array([np.random.choice(nodes, 2) for i in range(6000)])
df_record = pd.DataFrame(record, columns=['o', 'd'])
am = np.zeros((len(nodes), len(nodes)))

res = adjacent3(df_record, am)
res

array([[172., 174., 151., 157., 171., 162.],
       [153., 167., 160., 150., 183., 173.],
       [165., 177., 184., 157., 169., 169.],
       [179., 161., 166., 138., 157., 161.],
       [184., 193., 159., 160., 154., 179.],
       [188., 170., 159., 147., 166., 185.]])

See, this would eventually result in HUGE difference when you have a big dataset.

In [20]:
zones = pd.read_csv('dataset/taxi_zone_lookup.csv')

# very important globals:
yellow_zone = zones.loc[zones['Borough'] == 'Manhattan']

image_size = yellow_zone.shape[0]

# create a mapping {'district_id_in_data_source': index from 0 to 68}
real_id = list(map(str, list(yellow_zone.loc[:,'LocationID'])))
conv_id = [i for i in range(image_size)]

# create matrix id mapping
assert len(real_id) == len(conv_id)
mp = dict(zip(real_id, conv_id))
mp

{'4': 0,
 '12': 1,
 '13': 2,
 '24': 3,
 '41': 4,
 '42': 5,
 '43': 6,
 '45': 7,
 '48': 8,
 '50': 9,
 '68': 10,
 '74': 11,
 '75': 12,
 '79': 13,
 '87': 14,
 '88': 15,
 '90': 16,
 '100': 17,
 '103': 18,
 '104': 19,
 '105': 20,
 '107': 21,
 '113': 22,
 '114': 23,
 '116': 24,
 '120': 25,
 '125': 26,
 '127': 27,
 '128': 28,
 '137': 29,
 '140': 30,
 '141': 31,
 '142': 32,
 '143': 33,
 '144': 34,
 '148': 35,
 '151': 36,
 '152': 37,
 '153': 38,
 '158': 39,
 '161': 40,
 '162': 41,
 '163': 42,
 '164': 43,
 '166': 44,
 '170': 45,
 '186': 46,
 '194': 47,
 '202': 48,
 '209': 49,
 '211': 50,
 '224': 51,
 '229': 52,
 '230': 53,
 '231': 54,
 '232': 55,
 '233': 56,
 '234': 57,
 '236': 58,
 '237': 59,
 '238': 60,
 '239': 61,
 '243': 62,
 '244': 63,
 '246': 64,
 '249': 65,
 '261': 66,
 '262': 67,
 '263': 68}

In [21]:
import numba.types as types

dir(types)

['ABCMeta',
 'Any',
 'Array',
 'ArrayCTypes',
 'ArrayCompatible',
 'ArrayFlags',
 'ArrayIterator',
 'BaseAnonymousTuple',
 'BaseContainerIterator',
 'BaseContainerPayload',
 'BaseFunction',
 'BaseNamedTuple',
 'BaseTuple',
 'Boolean',
 'BoundFunction',
 'Buffer',
 'ByteArray',
 'Bytes',
 'CPointer',
 'Callable',
 'CharSeq',
 'ClassDataType',
 'ClassInstanceType',
 'ClassType',
 'Complex',
 'ConstSized',
 'Container',
 'ContextManager',
 'Conversion',
 'DType',
 'DTypeSpec',
 'DeferredType',
 'DictItemsIterableType',
 'DictIteratorType',
 'DictKeysIterableType',
 'DictType',
 'DictValuesIterableType',
 'Dispatcher',
 'Dummy',
 'EllipsisType',
 'EnumClass',
 'EnumMember',
 'EnumerateType',
 'EphemeralArray',
 'EphemeralPointer',
 'ExceptionClass',
 'ExceptionInstance',
 'ExternalFunction',
 'ExternalFunctionPointer',
 'Float',
 'Function',
 'Generator',
 'Hashable',
 'IntEnumClass',
 'IntEnumMember',
 'Integer',
 'IntegerLiteral',
 'IterableType',
 'IteratorType',
 'List',
 'ListIter',
 

In [29]:
type(np.arange(0, 69, dtype='int32')[0])

numpy.int32

In [32]:
a = np.arange(0,100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
a = a[:,(1,2)]
a

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])